// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_pbMlzO99lj_PZMiZEh3ApFB6FhftXXE',
    appId: '1:166415382222:web:98091bd1a9361647ec829f',
    messagingSenderId: '166415382222',
    projectId: 'fruttorto-8a5f9',
    authDomain: 'fruttorto-8a5f9.firebaseapp.com',
    storageBucket: 'fruttorto-8a5f9.firebasestorage.app',
    measurementId: 'G-T03JLQZX6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMyH0NNsuIeCMghaqf_MD78e72C3LL0ZQ',
    appId: '1:166415382222:android:d5a8cc66362d9eb8ec829f',
    messagingSenderId: '166415382222',
    projectId: 'fruttorto-8a5f9',
    storageBucket: 'fruttorto-8a5f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53npHqQ2RETZXYD1Gd-oZNgVmS5_pBVQ',
    appId: '1:166415382222:ios:b5ce104cc95b139eec829f',
    messagingSenderId: '166415382222',
    projectId: 'fruttorto-8a5f9',
    storageBucket: 'fruttorto-8a5f9.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC53npHqQ2RETZXYD1Gd-oZNgVmS5_pBVQ',
    appId: '1:166415382222:ios:b5ce104cc95b139eec829f',
    messagingSenderId: '166415382222',
    projectId: 'fruttorto-8a5f9',
    storageBucket: 'fruttorto-8a5f9.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_pbMlzO99lj_PZMiZEh3ApFB6FhftXXE',
    appId: '1:166415382222:web:2a11637b0ca5f70eec829f',
    messagingSenderId: '166415382222',
    projectId: 'fruttorto-8a5f9',
    authDomain: 'fruttorto-8a5f9.firebaseapp.com',
    storageBucket: 'fruttorto-8a5f9.firebasestorage.app',
    measurementId: 'G-88QD0ZMW4C',
  );
}
